services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: investimentos
      POSTGRES_USER: investmentuser
      POSTGRES_PASSWORD: 4HkfnjCzpfR
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:
    driver: local

networks:
  backend:
    driver: bridge
